### ISSUE TITLE
⛔️ Showing Recent Messages The package product 'GoogleAppMeasurement' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0

### ISSUE THREAD

**Issue by mezhevikin** [Koze/GoogleMobileAds-SPM#1]
Hi @Koze . 
I would like use GoogleMobileAds for SPM too.
And I'm ready to be a tester.
I create empty swift project on Xcode and added this repository to dependency.
And I'm getting an error:

```
Showing Recent Messages
The package product 'GoogleAppMeasurement' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0

```

I hope this information will be helpful for you!
If you need more information then let me know

_Xcode 12.4. Macbook Air M1. Minimum target 14.0_

**Comment by Koze** [comment]
Hi, @mezhevikin
I fixed the error about minimum version by changing deployment target iOS v10.
But now there is other problem that doesn't found headers. I'm trying to fix it. Thanks,

**Comment by mezhevikin** [comment]
@Koze Good luck! Let me know if you need a tester 👍

**Comment by Koze** [comment]
@mezhevikin I fixed the header problem and installation problem then updated the repository by force push. 
When you check updating, please use `Reset Package Caches` instead of `Update to Latest Package Version` with Xcode.

And then, I noticed that it needs to add following workaround script for installation the app like official Firebase SPM https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-694449182
```sh
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Frameworks/UserMessagingPlatform.framework"
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Frameworks/GoogleMobileAds.framework"
```

I tested simulator installing, device installing from Xcode and TestFlight installing. These look like working fine.

**Comment by Koze** [comment]
@mezhevikin Cloud you test the latest package?

**Comment by mezhevikin** [comment]
@Koze I tested it, now project compiled but I'm getting an error.

`*** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without AppMeasurement. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to include the AppMeasurement framework and set the -ObjC linker flag. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist'`

I added **-ObjC** linker flag to **Other Linker Flags** and it fixed the problem.
Is it possible to do this automatically using SPM?

**Comment by Koze** [comment]
@mezhevikin I researched but couldn't find a solution on the Swift package side.
**Other Linker Flags** looks like needed for target of the host project same as Firebase SPM described here.  
https://github.com/firebase/firebase-ios-sdk/blob/eca78c765a87d7c19ab390115a2dac0b0e5eca04/SwiftPackageManager.md  
> Analytics requires clients to add -ObjC linker option.

> If you've installed FirebaseAnalytics, Add the -ObjC option to Other Linker Flags in the Build Settings tab.

Firebase Analytics uses binary target, too. It's xcframework contains Objective-C sources.  
https://github.com/firebase/firebase-ios-sdk/blob/eca78c765a87d7c19ab390115a2dac0b0e5eca04/Package.swift#L246-L250

I'll write about **Other Linker Flags** to README.

**Comment by mezhevikin** [comment]
> I'll write about Other Linker Flags to README.

@Koze That's good idea. Thank you. Good job! Keep it up 😄
