### ISSUE TITLE
Found an unexpected Mach-O header code: 0x72613c21

### ISSUE THREAD

**Issue by mezhevikin** [Koze/GoogleMobileAds-SPM#2]
Hi @Koze ! It's me!
And I found the new problem.
When I'm trying upload app to the Appstore then I'm getting, en Error:

`Found an unexpected Mach-O header code: 0x72613c21`

I checked on the empty project with one dependency **GoogleMobileAds-SPM**.

<img width="300" src="https://user-images.githubusercontent.com/973364/108698639-6b4e7900-7515-11eb-99fe-00edfcbce6b1.png">

_Xcode 12.4. Macbook Air M1_

**Comment by Koze** [comment]
@mezhevikin 
I noticed that GoogleMobileAds has the dependency with GoogleAppMeasurement that is a xcframework binary.
https://github.com/google/GoogleAppMeasurement/blob/38205d8e39f806f71b048f93427337c9511c9402/Package.swift#L60-L64

So it needs one more line in the build script workaround.
```sh
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Frameworks/GoogleAppMeasurement.framework"
```
I will fix the README.

And I have a good news. Yesterday, I have updated the app in the App Store successfully with my AdMob SPM, Xcode 12.4 and MacBook Air M1.
My project uses Firebase SPM and the project already has the workaround script for GoogleAppMeasurement, so I didn't notice AdMob SPM needs this, too.
Please try to add above one line to the script.

**Comment by mezhevikin** [comment]
@Koze This solution works. 
But if I add a widget to the project, it breaks everything again.

**I have a good news too. Xcode 14.5 beta 2 fixed the problem.** It works without these hacks.
I will be wait the release version.

🎉 Congratulations on your purchase of a MacBook Air M1 and upgrading to SPM!

**Comment by Koze** [comment]
@mezhevikin 
https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-694449182
This workaround is basic and used for main app target.

When you have other target in your app, you may need to remove framework files for each target that contains it like these other workarounds.
https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-707793520
https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-771351512
https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-779417936

> Xcode 14.5 beta 2 fixed the problem.

It's so good news! It will be the best solution👍
