### ISSUE TITLE
💻 GoogleMobileAds 8.1 crash on iOS 13 sumulator and Apple Silicon M1

### ISSUE THREAD

**Issue by mezhevikin** [Koze/GoogleMobileAds-SPM#3]
Hi @Koze .
I found the new problem 🤔
This issue is not spm related, but I would like to get confirmation from other developers.

 GoogleMobileAds 8.1 crash on iOS 13 sumulator if you use Apple Silicon M1 processor.

`Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)`

The crash points to the AppDelegate class but the problem is in GADMobileAds.sharedInstance().start(). If you remove this method, the crash disappears.

Can you confirm or deny the problem? 

I have created topic on google developer forum:
https://groups.google.com/g/google-admob-ads-sdk/c/ulno5g6X9IA

**Comment by Koze** [comment]
@mezhevikin 
I found a simple workaround.
Setting any of the following diagnostic options in the scheme settings will prevent the crash.

- Address Sanitizer
- Thread Sanitizer
- Malloc Scribble
- Malloc Guard Edges
- Guard Malloc
- Malloc Stack Logging

<img width="956" alt="スクリーンショット 2021-03-09 9 14 51" src="https://user-images.githubusercontent.com/1420322/110400415-f0f82a00-80ba-11eb-88f6-c3abdd314c6c.png">

I verified this with Xcode 12.4 (12D4e), iOS 13.7 Simulator, macOS Big Sur 11.2.3（20D91） and M1 Apple Silicon Mac.

**Comment by Koze** [comment]
@mezhevikin 
According to my investigation, it has nothing to do with AdMob, xcframework, or SPM. The crash seems to be caused by a combination of Xcode 12, iOS 13 Simulator, Big Sur, and M1, even when using only system frameworks.

Please try my workaround. Thanks,

**Comment by mezhevikin** [comment]
Hi @Koze . I tried your workaround and it works perfectly.
Thank you.
I sent this information to Admob Team. I think it will be helpful in any case.

**Comment by mezhevikin** [comment]
Additional information:
This workaround works for iOS13 simulator, but does'n work for iOS 12.4 simulator.

**Comment by Koze** [comment]
> does'n work for iOS 12.4 simulator

I hope this will be fixed in a future version of Xcode.

**Comment by jolebowski** [comment]
Hi, I tried your solution but it doesn't work for me
