### ISSUE TITLE
Please update the assembly to 8.2.0

### ISSUE THREAD

**Issue by YurchukV** [Koze/GoogleMobileAds-SPM#4]

**Comment by Koze** [comment]
Thank you for the notification.
I updated GoogleMobileAds.xcframework binary to newest 8.2.0.
https://github.com/Koze/GoogleMobileAds-SPM/releases/tag/8.2.0

**Comment by Koze** [comment]
@YurchukV 
Thank you for the notification.
I updated GoogleMobileAds.xcframework binary to newest 8.2.0.
https://github.com/Koze/GoogleMobileAds-SPM/releases/tag/8.2.0
Please check it.
