### ISSUE TITLE
Update to 8.4.0

### ISSUE THREAD

**Issue by mezhevikin** [Koze/GoogleMobileAds-SPM#6]
Hi @Koze . Can you update repo to 8.4.0?
I tried do it myself, but I'm getting an error:

<img width="721" alt="Screenshot 2021-04-21 at 10 22 12" src="https://user-images.githubusercontent.com/973364/115513206-7a3e7700-a28b-11eb-9bd5-7562d3c183bd.png">

**Comment by mezhevikin** [comment]
Fixed. If you need 8.4.0 you can use my fork - https://github.com/mezhevikin/GoogleMobileAds-SPM

**Comment by Koze** [comment]
@mezhevikin
Sorry for late response. Today I was working to update this repository for AdMob SDK 8.3.0 and 8.4.0.
And I pushed just a while ago. Thanks.
