### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by YurchukV** [Koze/GoogleMobileAds-SPM#8]
Hello, please add support Google Analytics

**Comment by Koze** [comment]
@YurchukV
You can use Google Analytics as Swift Package via Firebase.
Here is the document for introduction in the Firebase SDK repository.
https://github.com/firebase/firebase-ios-sdk/blob/c0df01d5f0141dfe7d6d48efceb086219171a1cd/SwiftPackageManager.md

If you want to use AdMob and Analytics, you can setup each this repository and Firebase repository as Swift Package.
