### ISSUE TITLE
Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)

### ISSUE THREAD

**Issue by jolebowski** [Koze/GoogleMobileAds-SPM#9]
When I launch my application I get the error 

I have an M1 too

**Comment by Koze** [comment]
@jolebowski 
I use this repository with latest Xcode 13.2.1 with iOS app target and there is no problem.
How about your version of Xcode, platform of the app, deployment target version or etc.

FIY: There is crash bug for deployment with Xcode 13.2, you needs to use Xcode 13.2.1.
Please check below link describing a bug number 86390060.
https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2_1-release-notes
